type Maybe<T> = T | null;

export type AttractionDetail = {
  assistiveListening: boolean,
  audioDescription: boolean,
  categoryCode: string,
  climateControlled: boolean,
  crazyThreshold: number,
  duration: number,
  fastpassBooth: boolean,
  fastpassOnly: boolean,
  frightening: boolean,
  handheldCaptioning: boolean,
  heightRestriction: Maybe<unknown>,
  latitude: string,
  longitude: string,
  matchName: string,
  name: string,
  noServiceAnimals: boolean,
  notToBeMissed: boolean,
  openEmhEvening: boolean,
  openEmhMorning: boolean,
  openNotSoScary: boolean,
  openVeryMerry: boolean,
  openedOn: string,
  operationalNotes: Maybe<unknown>,
  operatorType: string,
  riderSwap: boolean,
  seasonal: boolean,
  signLanguage: boolean,
  singleRider: boolean,
  whatItIs: string,
  whenToGo: Maybe<unknown>,
};
