import { gql } from 'apollo-server';

export const Restaurant = gql`
  type Restaurant {
    id: Int!
    name: String
    permalink: String
  }
`;

/*
 *            "id": 24,
            "land_id": 1,
            "name": "Casey's Corner",
            "permalink": "caseys-corner",
            "category_code": "counter_service",
            "portion_size": "Medium",
            "cost_code": null,
            "cuisine": "American",
            "phone_number": null,
            "entree_range": null,
            "when_to_go": null,
            "parking": null,
            "bar": null,
            "wine_list": null,
            "dress": "Casual",
            "awards": null,
            "breakfast_hours": null,
            "lunch_hours": null,
            "dinner_hours": null,
            "selection": "Hot dogs, corn-dog nuggets, fries, and brownies.",
            "setting_atmosphere": null,
            "other_recommendations": null,
            "summary": "Casey’s hot dogs aren’t anywhere near as good as those at the <a href=\"http://touringplans.com/magic-kingdom/dining/liberty-square-market\">Liberty Square Market</a>. The main reason to visit Casey’s now is their addictive corn-dog nuggets. ",
            "house_specialties": null,
            "counter_quality_rating": "Fair",
            "counter_value_rating": "B",
            "table_quality_rating": null,
            "table_value_rating": null,
            "overall_rating": null,
            "service_rating": null,
            "friendliness_rating": null,
            "thumbs_up": 85,
            "adult_breakfast_menu_url": null,
            "adult_lunch_menu_url": "http://allears.net/menu/men_cas.htm",
            "adult_dinner_menu_url": "http://allears.net/menu/men_cas.htm",
            "child_breakfast_menu_url": null,
            "child_lunch_menu_url": null,
            "child_dinner_menu_url": null,
            "requires_credit_card": false,
            "requires_pre_payment": false,
            "created_at": "2010-08-26T23:28:57.000-04:00",
            "updated_at": "2019-04-05T11:59:27.000-04:00",
            "plan_x_coord": 280,
            "plan_y_coord": 261,
            "old_park_id": 1,
            "old_attraction_id": 55,
            "plan_name": "Dine at Casey's Corner",
            "extinct_on": null,
            "opened_on": null,
            "disney_permalink": null,
            "code": "ORL024",
            "short_name": "Casey's Corner",
            "accepts_reservations": false,
            "kosher_available": false,
            "dinable_id": 1,
            "dinable_type": "Park",
            "location_details": null,
            "operator_id": null,
            "operator_url": null,
            "operator_type": null,
            "walking_time_proxy_id": null,
            "sort_name": "caseys corner",
            "mobile_ordering": true,
            "extinct_on_uncertain": null,
            "opened_on_uncertain": null,
            "opened_on_known": null
            */
