import { CamelCasedProperties } from 'type-fest';

type Maybe<T> = T | null;

export enum ParkPermalink {
  MagicKingdom = 'magic-kingdom',
  Epcot = 'epcot',
  AnimalKingdom = 'animal-kingdom',
  HollywoodStudios = 'hollywood-studios',
}

export type AttractionRaw = {
  name: string,
  short_name: string;
  permalink: string,
};

export type Attraction = CamelCasedProperties<AttractionRaw> & {
  detail?: AttractionDetail,
};

export type AttractionDetailRaw = {
  allow_showtimes_after_close: boolean,
  allow_time_restriction: boolean,
  arrive_before: number,
  arrive_before_fp: number,
  assistive_listening: boolean,
  audio_description: boolean,
  average_wait_assumes: Maybe<unknown>,
  average_wait_per_hundred: Maybe<unknown>,
  category_code: string,
  climate_controlled: boolean,
  close_at_dusk: Maybe<unknown>,
  closing_round_code: Maybe<unknown>,
  crazy_threshold: number,
  created_at: Date,
  crowd_calendar_version: number,
  disconnected_fastpass_booth: boolean,
  duration: number,
  extinct_on: Maybe<unknown>,
  extinct_on_uncertain: Maybe<unknown>,
  extra_cost: boolean,
  fastpass_booth: boolean,
  fastpass_only: boolean,
  flexible_duration: Maybe<unknown>,
  frightening: boolean,
  handheld_captioning: boolean,
  height_restriction: Maybe<unknown>,
  hide_app: boolean,
  ignore_scrapes: boolean,
  intense: boolean,
  latitude: string,
  loading_speed: Maybe<unknown>,
  longitude: string,
  masthead_circle_x: Maybe<unknown>,
  masthead_circle_y: Maybe<unknown>,
  match_name: string,
  name: string,
  no_service_animals: boolean,
  not_to_be_missed: boolean,
  open_emh_evening: boolean,
  open_emh_morning: boolean,
  open_not_so_scary: boolean,
  open_very_merry: boolean,
  opened_on: string,
  opened_on_known: Maybe<unknown>,
  opened_on_uncertain: Maybe<unknown>,
  operational_notes: Maybe<unknown>,
  operator_id: number,
  operator_type: string,
  park_entrance: boolean,
  physical_considerations: boolean,
  probable_wait_time: Maybe<unknown>,
  reflective_captioning: boolean,
  relative_close: Maybe<unknown>,
  relative_close_to_sunset: Maybe<unknown>,
  relative_open: Maybe<unknown>,
  relative_open_to_sunset: Maybe<unknown>,
  rider_swap: boolean,
  scheduled_code: Maybe<unknown>,
  scope_and_scale_code: string,
  seasonal: boolean,
  service_animal_check: boolean,
  short_name: string,
  showtime_proxy_id: Maybe<unknown>,
  sign_language: boolean,
  single_rider: boolean,
  sort_name: string,
  special_needs: Maybe<unknown>,
  time_zone: string,
  ultimate_code: string,
  ultimate_task: string,
  updated_at: Date,
  video_captioning: boolean,
  walking_time_proxy_id: Maybe<unknown>,
  wet: boolean,
  what_it_is: string,
  wheelchair_transfer_code: Maybe<unknown>,
  when_to_go: Maybe<unknown>,
};

export type AttractionDetail = CamelCasedProperties<AttractionDetailRaw>;
